### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by myst729** [xudafeng/AStar#1]
同样的位置，起点和终点对调以后路径不一样，长度也不一样。看你的实现好像直走和斜走cost是相同的

![image](https://cloud.githubusercontent.com/assets/519733/5070865/51f10d28-6ea6-11e4-8c72-2e4c4a438c24.png) ![image](https://cloud.githubusercontent.com/assets/519733/5070868/59d132c0-6ea6-11e4-87f2-18e43d32fb4a.png)

**Comment by xudafeng** [comment]
@myst729 是可以设置斜角的，diagonal关闭就好了

**Comment by myst729** [comment]
设置如下，一直没变过
![image](https://cloud.githubusercontent.com/assets/519733/5081658/c5c872c4-6f0d-11e4-8d84-068692b85e27.png)

往返路线长度是不一样的
![image](https://cloud.githubusercontent.com/assets/519733/5081901/79525cd0-6f11-11e4-91a3-53ee91541a6e.png) ![image](https://cloud.githubusercontent.com/assets/519733/5081902/845b5f0a-6f11-11e4-91a2-be2f673cd697.png)

另一个例子（根据你的实现，斜走和直走增加的`G`都是 1）
![image](https://cloud.githubusercontent.com/assets/519733/5081915/b45f6278-6f11-11e4-8937-15067ec96571.png) ![image](https://cloud.githubusercontent.com/assets/519733/5081916/ba7a17a2-6f11-11e4-9b81-8aafcbe414ab.png)

同样的端点，往返路线可以不同，但长度不应该不一样，斜走部分的实现应该是有问题的。

**Comment by myst729** [comment]
`Matrix.prototype.rightDown` 实现错了

![image](https://cloud.githubusercontent.com/assets/519733/5082159/55a1a462-6f16-11e4-9649-a687b4aad688.png)

**Comment by myst729** [comment]
neighbors 获取是这个算法的一部分。除了正方形网格，类似下面这样的地图
![image](https://cloud.githubusercontent.com/assets/519733/5082275/6fec4dc0-6f18-11e4-97d3-fd2bc825e4ef.png)

还有更复杂的正多边形镶嵌
![image](https://cloud.githubusercontent.com/assets/519733/5082284/9590b69c-6f18-11e4-8834-088c921752ef.png)

甚至不规则多边形镶嵌，差异都是在对 neighbor 的计算和处理上。这个应该是算法的可配置部分，建议还是不要放到算法外部吧。（不过我也只实现了正方形网格，懒……）
